// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import React from 'react';
import { createRoot } from 'react-dom/client';

function NavigationBar() {
  // TODO: Actually implement a navigation bar
  return <h1>Hello from React!</h1>;
}

const domNode = document.getElementById('navigation');
const root = createRoot(domNode);
root.render(<NavigationBar />);

import { application } from "./application"

import ComputerCardsController from "./computer_cards_controller"
application.register("computer-cards", ComputerCardsController)

import GearSelectionController from "./gear_selection_controller"
application.register("gear-selection", GearSelectionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PlayAttackController from "./play_attack_controller"
application.register("play-attack", PlayAttackController)

import UserCardsController from "./user_cards_controller"
application.register("user-cards", UserCardsController)
